### ISSUE TITLE
请问可以分享下生成的结果吗

### ISSUE THREAD

**Issue by Mercury1010** [wyhuai/NeRFocus#2]
作者你好，因为每次测试都只能生成一张图的结果，并且速度非常慢，所以冒昧询问有没有测试集所有生成的结果，非常感谢！

**Comment by wyhuai** [comment]
> 

Here are the video results: 
![image](https://user-images.githubusercontent.com/95485229/185051215-ee2f6d57-aa00-4628-8b18-1e01c1ca8363.png)

**Comment by wyhuai** [comment]
> 作者你好，因为每次测试都只能生成一张图的结果，并且速度非常慢，所以冒昧询问有没有测试集所有生成的结果，非常感谢！
Here are the video results:
![image](https://user-images.githubusercontent.com/95485229/185051312-46a87c01-bba5-411f-b0ae-c4dfcf393c39.png)

**Comment by Mercury1010** [comment]
> > 作者你好，因为每次测试都只能生成一张图的结果，并且速度非常慢，所以冒昧询问有没有测试集所有生成的结果，非常感谢！
> > Here are the video results:
> > ![image](https://user-images.githubusercontent.com/95485229/185051312-46a87c01-bba5-411f-b0ae-c4dfcf393c39.png)

谢谢哈，我是需要生成的图像做数据集，不过之前是没好好看代码，以为一次只能生成一张，刚才发现是有这个代码的，不好意思麻烦了，祝科研顺利~
